name: OCI Factory Workflows - Build BusyBox Rock

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: canonical/oci-factory/.github/workflows/Build-Rock.yaml@main
    with:
      oci-archive-name: "busybox-rock"
      rock-repo: rockcrafters/busybox-rock
      rock-repo-commit: main
      rockfile-directory: .
      arch-map: '{"amd64": ["ubuntu-latest"]}'

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/download-artifact@v4
        with:
          name: busybox-rock

      - name: 'Set up skopeo'
        uses: warjiang/setup-skopeo@main
        with:
          version: latest

      - run: skopeo copy --multi-arch all oci-archive:busybox-rock docker://ghcr.io/rockcrafters/busybox-rock/busybox:latest